name: Sign and Upload APK

on:
  push:
    branches:
      - 'deployed'
  pull_request:
    branches:
      - 'deployed'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Find cacerts
        run: |
          find / -name cacerts 2>/dev/null

      # Configurar Node.js
      - name: Configuraci贸n de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Prepare Android SDK Build Tools
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
            mkdir -p $HOME/android-sdk/
            unzip commandlinetools.zip -d $HOME/android-sdk/
            echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
            echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
            echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
            source $GITHUB_ENV

      - name: Install Android SDK Build Tools
        run: |
            yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME
            $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;34.0.0" --sdk_root=$ANDROID_HOME

      # Instalar dependencias con npm
      - name: Instalaci贸n de dependencias
        run: npm install

      # Actualizar la versi贸n
      - name: Increment version
        run: |
          VERSION_FILE=version.properties
          if [ -f "$VERSION_FILE" ]; then
            . $VERSION_FILE
            PATCH_VERSION=$((PATCH_VERSION+1))
          else
            MAJOR_VERSION=1
            MINOR_VERSION=0
            PATCH_VERSION=0
          fi
          echo "MAJOR_VERSION=$MAJOR_VERSION" > $VERSION_FILE
          echo "MINOR_VERSION=$MINOR_VERSION" >> $VERSION_FILE
          echo "PATCH_VERSION=$PATCH_VERSION" >> $VERSION_FILE
          echo "VERSION=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION" >> $VERSION_FILE
          echo "Updated version to $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"

      # Usar la versi贸n en el build.gradle
      - name: Set version in Gradle
        run: |
          VERSION=$(awk -F'=' '/^VERSION=/{print $2}' version.properties | xargs)
          sed -i "s/versionName \".*\"/versionName \"$VERSION\"/" android/app/build.gradle

      - name: Generate temporary signing key
        env:
          KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD:  ${{ secrets.SIGNING_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          keytool -genkeypair \
            -alias "abc-call" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Temporary, OU=Actions, O=GitHub, L=Cloud, ST=DevOps, C=US" \
            -keypass "abc-call" \
            -keystore release-keystore.jks \
            -storepass "abc-call"

      - name: Build release APK
        run: npm run pipeline:build-release

      - name: Sign APK
        env:
          KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          UNSIGNED_APK: android/app/build/outputs/apk/release/app-release.apk
          SIGNED_APK: android/app/build/outputs/apk/release/app-release-signed.apk
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks release-keystore.jks \
            --ks-key-alias "abc-call" \
            --ks-pass pass:"abc-call" \
            --key-pass pass:"abc-call" \
            --out "$SIGNED_APK" \
            "$UNSIGNED_APK"
      
      - name: List apks
        run: ls -ltha android/app/build/outputs/apk/release/
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Signed app bundle
          #path: ${{steps.sign_app.outputs.signedReleaseFile}}
          path: android/app/build/outputs/apk/release
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: Signed app bundle
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verificacion de directorios
        run: ls -ltha

      - name: Upload non-signed apk to S3 Bucket
        run: |
          aws s3 cp app-release.apk s3://${{ vars.S3_BUCKET_NAME }}/app-release.apk

      - name: Upload signed apk to S3 Bucket
        run: |
          aws s3 cp app-release.apk s3://${{ vars.S3_BUCKET_NAME }}/app-release-signed.apk